name = "MJX Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8ab7c48d44c37faf62a2007ef59b1a39cf2f8f31c1562db14d5e1bee588fa06"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
