name = "MJX Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa22d9122e8d689610ac3b2216529a49e575b9ccfb90337848df34c78ff22a6c"

[versions]
forge = "47.4.23"
minecraft = "1.20.1"
